module.exports = {
    apps: [
        {
            name: 'bolajoon',
            script: 'server.js',
            cwd: '/var/www/bolajoon',
            env: {
                NODE_ENV: 'production',
                MONGODB_URI: 'mongodb+srv://bolajoon:bolajoon2026@cluster0.izqixhj.mongodb.net/?appName=Cluster0',
                JWT_SECRET: 'your-super-secret-jwt-key-change-this-in-production',
                JWT_EXPIRES_IN: '7d',
                NEXT_PUBLIC_APP_NAME: 'Bolajoon.uz',
                NEXT_PUBLIC_APP_URL: 'https://bolajoon.uz',
                NEXT_PUBLIC_API_URL: 'https://bolajoon.uz',
                TELEGRAM_BOT_TOKEN: '8123574882:AAH7h-BM2zInWdln4RwPVoYZfaOjqLbSkXI',
                TELEGRAM_CHAT_ID: '-1003764341768',
                CRON_SECRET: 'bolajon-cron-secret-2024',
                PAYME_MERCHANT_ID: '69874b603ae533b283c2aa8f',
                PAYME_SECRET_KEY: 'Bb9@yH@EVrfXZDVCej&pSG?BJyeyCN2nXHk0',
                PAYME_ENDPOINT: 'https://checkout.paycom.uz/api',
                BOT_API_SECRET: 'bj-bot-secret-2026-xK9mP3qRvNw'
            },
            instances: 1,
            exec_mode: 'fork',
            autorestart: true,
            watch: false,
            max_memory_restart: '512M',
            error_file: '/var/www/bolajoon/logs/app-error.log',
            out_file: '/var/www/bolajoon/logs/app-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
        },
        {
            name: 'bolajoon-bot',
            script: 'lead-bot/index.js',
            cwd: '/var/www/bolajoon',
            env_production: {
                NODE_ENV: 'production',
            },
            instances: 1,
            exec_mode: 'fork',
            autorestart: true,
            watch: false,
            max_memory_restart: '128M',
            error_file: '/var/www/bolajoon/logs/bot-error.log',
            out_file: '/var/www/bolajoon/logs/bot-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
        },
    ],
};
